FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

COPY ./scripts/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 